### ISSUE TITLE
Installing the library including all the requirements.

### ISSUE THREAD

**Issue by Andresfgomez970** [scikit-hep/pylhe#119]
Hello everyone,

I was just installing the library using `pip install pylhe`. However, after running this command I check that awkward was not installed despite the fact that it is in the variable `install_requires` in the setup.cfg file. I just show the output from running pip install pylhe: 

Requirement already satisfied: pylhe in path_to_packages/site-packages (0.2.1)
Requirement already satisfied: networkx~=2.2 in path_to_packages/site-packages (from pylhe) (2.8)
Requirement already satisfied: tex2pix~=0.3 in path_to_packages/site-packages (from pylhe) (0.3.1)
Requirement already satisfied: particle~=0.14 in path_to_packages/site-packages (from pylhe) (0.20.1)
Requirement already satisfied: attrs>=19.2 in path_to_packages/site-packages (from particle~=0.14->pylhe) (21.4.0)
Requirement already satisfied: hepunits>=2.0.0 in path_to_packages/site-packages (from particle~=0.14->pylhe) (2.2.0)

I installed the library with all the requirements without problem cloning the repo and running `python setup.py install`. If there is a different standard for a correct installation with all the requirements I will be happy to hear it.

**Comment by matthewfeickert** [comment]
> I was just installing the library using `pip install pylhe`. However, after running this command I check that awkward was not installed despite the fact that it is in the variable `install_requires` in the setup.cfg file.

@Andresfgomez970 We need to make a new release but there are a few things that we should fix before doing so (hence it being delayed &mdash though thanks to Eduardo for helping out to move things forward). The last release was [`v0.2.1`](https://github.com/scikit-hep/pylhe/releases/tag/v0.2.1) in April 2nd 2021, and `awkward`

https://github.com/scikit-hep/pylhe/blob/799b0ef598bb618815ddf06719d966bb71165567/setup.cfg#L35-L40

wasn't added until PR #83 on April 17th, 2021. So `v0.2.1` doesn't have it as a dependency.

> I installed the library with all the requirements without problem cloning the repo and running `python setup.py install`. If there is a different standard for a correct installation with all the requirements I will be happy to hear it.

Please do not use `python setup.py install` anymore as [that behavior is considered very deprecated](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html). For all installs of Python packages use `pip`. So for a local install, clone the repository and then from the top level inside of your Python virtual environment that you're using run

```console
$ python -m pip install .
```

@Andresfgomez970 I'm going to close this Issue, but if you have further questions related to this Issue please continue to post here and we can discuss as needed. :+1:

**Comment by matthewfeickert** [comment]
@Andresfgomez970 you might already be doing this, but to get notifications from GitHub when there is a new release you can subscribe to get notifications specifically for them.

![subscribed](https://user-images.githubusercontent.com/5142394/165029306-149d7478-854d-4173-a51a-435caf4803fd.png)

I can try to also remember to come back and ping you here when the next release goes out.
