### ISSUE TITLE
Add pylhe to Conda

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/pylhe#128]
This seems like a good idea in general. It is a requirement in order to get `pylhe` included in the `scikit-hep` metapackage, which is something many are keen on, see https://github.com/scikit-hep/scikit-hep/issues/173.

**Comment by matthewfeickert** [comment]
Easy to do, especially now that https://github.com/conda-incubator/grayskull exists and can generate the recipe for you. I'll open a PR today.
