### ISSUE TITLE
use scikit-hep.vector objects for momenta

### ISSUE THREAD

**Issue by tomeichlersmith** [scikit-hep/pylhe#194]
I find myself often using the following syntax
```python
momentum = vector.Array(ak.flatten(array_from_lhe[<some selection>]['vector']))
```
so that I can use [vector](https://github.com/scikit-hep/vector)'s helper functions for calculating common variables.
I get the `array_from_lhe` by using `pylhe.to_awkward(pylhe.read_lhe(<some file>))`.

To me, from the outside, the existence of the `Momentum4D` record within the awkward array returned by `pylhe.to_awkward` seems to be extraneous especially since we have a module with a known awkward interface and designed for 4D vectors. Is replacing `Momentum4D` with vector's `Vector4D` something that is feasible? If this isn't feasible (or desirable) for some reason, this isn't too much boilerplate code to do what I want, I was just curious.

**Comment by matthewfeickert** [comment]
@tomeichlersmith so you're saying that instead of the `"vector"` field returning an Awkward Array

```python
>>> import pylhe
>>> import skhep_testdata
>>> test_file = skhep_testdata.data_path("pylhe-testfile-pr29.lhe")
>>> example_array = pylhe.to_awkward(pylhe.read_lhe_with_attributes(test_file))
>>> example_array["particles"]["vector"]
<Array [[{x: -0.315, y: -0.63, ... t: 9.35}]] type='791 * var * Momentum4D["x": ...'>
```

you want it to return a vector `VectorArray4D`

```python
>>> import awkward as ak
>>> import vector
>>> vector.Array(ak.flatten(example_array["particles"]["vector"]))
<VectorArray4D [{x: -0.315, y: -0.63, ... t: 9.35}] type='3027 * Vector4D["x": f...'>
```
?

That seems pretty reasonable to me. Do you want to make a PR for this?

**Comment by tomeichlersmith** [comment]
Yea, I can work on it :+1: just wanted to make sure it was reasonable before starting

**Comment by lukasheinrich** [comment]
hi @tomeichlersmith -

I thought the fact that we register `vector`

via

https://github.com/scikit-hep/pylhe/blob/main/src/pylhe/awkward.py#L12

should make all the typical methods (like .mass) available for the `Momentum4D` array. Is this not the case?

**Comment by tomeichlersmith** [comment]
It does not appear like that registration is working as intended, doing the same thing as above:
```python
import pylhe
import skhep_testdata
test_file = skhep_testdata.data_path("pylhe-testfile-pr29.lhe")
example_array = pylhe.to_awkward(pylhe.read_lhe_with_attributes(test_file))
example_array["particles"]["vector"].mass

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 5
      3 test_file = skhep_testdata.data_path("pylhe-testfile-pr29.lhe")
      4 example_array = pylhe.to_awkward(pylhe.read_lhe_with_attributes(test_file))
----> 5 example_array["particles"]["vector"].mass

File /opt/conda/lib/python3.10/site-packages/awkward/highlevel.py:1120, in Array.__getattr__(self, where)
   1113         raise ak._errors.wrap_error(
   1114             AttributeError(
   1115                 "while trying to get field {}, an exception "
   1116                 "occurred:\n{}: {}".format(repr(where), type(err), str(err))
   1117             )
   1118         ) from err
   1119 else:
-> 1120     raise ak._errors.wrap_error(AttributeError(f"no field named {where!r}"))

AttributeError: no field named 'mass'
```

**Comment by lukasheinrich** [comment]
so this example breaks for you?

https://github.com/scikit-hep/pylhe/blob/main/examples/awkward_example.ipynb

**Comment by tomeichlersmith** [comment]
Nope :face_exhaling: that example works, I've just been forgetting the
```python
pylhe.register_awkward()
```
line.

Maybe since `awkward` is a required dependency of `pylhe` now, this registration could happen automatically at `import` time?

**Comment by lukasheinrich** [comment]
Oh nice - yeah if we have it as a required dep we could do this automatically - @matthewfeickert what do you think? that should be a much easier PR :)

**Comment by matthewfeickert** [comment]
> Oh nice - yeah if we have it as a required dep we could do this automatically - @matthewfeickert what do you think? that should be a much easier PR :)

SGTM. :+1:
