### ISSUE TITLE
Test file for everyone

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/pylhe#22]
I would suggest that you add to the notebook a test file so that anyone can trivially get a feeling for the package, running the thing with no need for anything else. Right now the notebook makes use of a private file. You could also get a test file in our package sciki-hep-testdata and use it from there …

BTW, most project packages have notebooks under `notebooks/` rather than `examples/`. Could you consider changing the name?

Thanks.

**Comment by lukasheinrich** [comment]
done via https://github.com/scikit-hep/scikit-hep-testdata/pull/32

**Comment by eduardo-rodrigues** [comment]
Cool. You mean the notebook example now uses the file in scikit-hep-testdata? Ideal.

**Comment by matthewfeickert** [comment]
> You mean the notebook example now uses the file in scikit-hep-testdata?

No this still needs to be resolved. There is now a test file though.

**Comment by eduardo-rodrigues** [comment]
Fair enough. Thanks @matthewfeickert.
