### ISSUE TITLE
Write LHE file function

### ISSUE THREAD

**Issue by APN-Pucky** [scikit-hep/pylhe#229]
Since powheg does not follow the lhe-3 standard strictly (i.e. weights see  #220 ), I think pylhe would be very nice to convert powheg lhe files to lhe-3 standard. Since pylhe can already read those lhe files one only needs to write the loaded lhe-data from pylhe.
Does pylhe have a write_lhe function? I have not seen one.

I'll write it very soon, just wanted to check if this exists somewhere already or has been done before?

**Comment by matthewfeickert** [comment]
> Does pylhe have a write_lhe function? I have not seen one.

@APN-Pucky Nope. Would be a welcome contribution I think. Go for it. :+1:
