### ISSUE TITLE
Drop Python 2.7 support

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pylhe#43]
Following the discussion RE: how to properly drop support for a release in https://github.com/scikit-hep/pyhf/issues/1075, it seems that as only Python 3.6+ is tested in CI now that either Python 2.7 support should be dropped or we should test Python 2.7 make a statement about how long Python 2.7 support will be provided in the `README`. Either way we should add a `python_requires` to `setup.cfg`.

Thoughts @lukasheinrich?

**Comment by matthewfeickert** [comment]
What I would actually recommend doing is cutting a release `v0.1.0` that has `python_requires >= 2.7` and then as soon as that is out cut release `v0.2.0` that has `python _requires >= 3.6`.

**Comment by lukasheinrich** [comment]
@matthewfeickert that sound pretty reasonable to me!

**Comment by matthewfeickert** [comment]
> that sound pretty reasonable to me!

Okay. Once the CI unfreezes for MacOS tests I'll setup PRs and then also make releases.

**Comment by eduardo-rodrigues** [comment]
Yep. See also our org guidelines/thoughts that we had put up some months ago - https://scikit-hep.org/supported-python-versions.

**Comment by eduardo-rodrigues** [comment]
This being said, it would be a *big* shame if the nice improvements/enhancements in https://github.com/scikit-hep/pylhe/pull/27 do not make it to the 1.0.0 release. I don't think there's much work on this PR to be done, to get it merged ... I can help for the parts related to `Particle`, BTW.

**Comment by matthewfeickert** [comment]
> Yep. See also our org guidelines/thoughts that we had put up some months ago

Yup I knew about them and I agree sticking to those is important. As @lukasheinrich better who some of the theory people are who are currently using `pylhe` than I do I wanted to make sure that we didn't break things for them, but making a `v0.1.0` release with `python_requires>=2.7` will ensure that there is a release that we can have for them if they're stuck for whatever reason.

> not make it to the 1.0.0 release

I think that a `v1.0.0` release is a _long_ way off, as we're all hesitant to freeze the API (and the library structure itself needs work as well). 

> I don't think there's much work on this PR to be done, to get it merged

We should probably discuss with the PR authors on the PR if they are going to come back to it, or if we should rebase it ourselves and then finish it off to get it in.

**Comment by hugovk** [comment]
> What I would actually recommend doing is cutting a release `v0.1.0` that has `python_requires >= 2.7` and then as soon as that is out cut release `v0.2.0` that has `python_requires >= 3.6`. This would make sure that we wouldn't break future installs on Python 2.7.

:+1:

btw, let's say `v0.1.0` was released _without_ `python_requires >= 2.7`, and `v0.2.0` with `python_requires >= 3.6`, and I have Python 2.7: pip would (correctly) reject `v0.2.0` due to `python_requires`.

It'd then check `v0.1.0` and (correctly) select that, because, well, there's no `python_requires` to tell it otherwise.

I still agree it's good to explicitly include it!

---

btw2

> What I would actually recommend doing is cutting a release `v0.1.0` that has `python_requires >= 2.7`

Yep, and exclude the early 3.x versions too. So if 2.7 and 3.6+ are supported:

```python
python_requires=">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*",
```

**Comment by matthewfeickert** [comment]
@hugovk Yup. c.f. [the discussion above](https://github.com/scikit-hep/pylhe/issues/43#issuecomment-700300427).

**Comment by matthewfeickert** [comment]
> It'd then check v0.1.0 and (correctly) select that, because, well, there's no python_requires to tell it otherwise.

@hugovk I don't think this is correct, given the discussions we've been having with Henry on https://github.com/scikit-hep/pyhf/issues/1075 and https://github.com/scikit-hep/iminuit/issues/494

> Yep, and exclude the early 3.x versions too

Those releases aren't explicitly tested. There's no breaking syntax in here, but I guess I see the point.

**Comment by hugovk** [comment]
> > Yep, and exclude the early 3.x versions too
> 
> The motivation for `v0.1.0` being that those releases aren't explicitly tested, right? There's no breaking syntax in here, but I guess I see the point that we should be explicitly making clear to `pip` what is and isn't supported Python runtimes.

Yeah, something like that. Some of the really old ones like 3.2 did Unicode a bit weirdly, so I wouldn't be surprised if they were already broken. Then again, if you're on 3.2 then you know if it's already broken!

But if you think it might work for 3.4/3.5, you might as well keep those allowed until `python_requires >= 3.6` comes along. 

Adding a version to `python_requires` is most important when at the boundary of (explicitly) dropping a version.

Sorry if I've made things more confusing, the original plan is good!

**Comment by matthewfeickert** [comment]
> Sorry if I've made things more confusing, the original plan is good!

No, your input is welcome so thanks for taking time to share it. :+1: Also nice to have developers with lots of experience give additional validation that things are on the right track. :slightly_smiling_face:

**Comment by eduardo-rodrigues** [comment]
> I think that a `v1.0.0` release is a _long_ way off, as we're all hesitant to freeze the API (and the library structure itself needs work as well).

Fair enough. I should have said ``v0.1.0 :D.
