### ISSUE TITLE
Include ability to read gzip'ed input LHE file

### ISSUE THREAD

**Issue by gridge** [scikit-hep/pylhe#65]
As a quick suggestion for an improvement, it might be very handy to include the ability of opening zipped lhe files without the need for unzipping beforehand.
This can be achieved checking the file type and in case using something like
https://stackoverflow.com/questions/10566558/python-read-lines-from-compressed-text-files

This feature can be then disabled if the right dependency is not there, but it looks to me a rather minimal dependency and a quite wide usage for this feature.

 Thanks for considering it.

**Comment by matthewfeickert** [comment]
> As a quick suggestion for an improvement, it might be very handy to include the ability of opening zipped lhe files without the need for unzipping beforehand.

Thanks for the Issue @gridge. All of the dev team is currently on winter holidays, but we'll look into this once we're back in 2021. This is a pretty easy to add feature request though, so should be doable. :+1:  PRs are of course always welcome though! (Aside: while we still need to [add a `CONTRIBUTING.md` to `pylhe`](https://github.com/scikit-hep/pylhe/issues/31) a good standin is to check out [the Scikit-HEP developer guidelines](https://scikit-hep.org/developer/intro))

> This feature can be then disabled if the right dependency is not there, but it looks to me a rather minimal dependency and a quite wide usage for this feature.

All the necessary libraries should be part of the Python 3 standard library, so this shouldn't be an issue.

**Comment by matthewfeickert** [comment]
Okay, so the work that needs to be done is to figure out how to get `gzip.open` to work with `xml.etree.ElementTree.iterparse`

https://github.com/scikit-hep/pylhe/blob/976aa365838470513906045155cf94e7d8e3dae6/src/pylhe/__init__.py#L166-L168

but from interactive tests it seems that this already works, so it should just be checking what `thefile` is and then extracting it with `gzip` if it is compressed.

**Comment by matthewfeickert** [comment]
@gridge [Release `v0.2.1`](https://pypi.org/project/pylhe/0.2.1/) should now support this, so if you just `python -m pip install --upgrade pylhe` you should be able to get it. Please let us know if you run into additional problems

**Comment by gridge** [comment]
That's great, thanks @matthewfeickert !!

**Comment by matthewfeickert** [comment]
Great to hear, @gridge. Please note Issue #79 and PR #80 though. We'll try to get a release that deals with that and a few other things out next week, but if it is a big problem now we can accelerate a release.

**Comment by gridge** [comment]
Thanks for pointing them out. So far I did not encounter problems but I'll keep those in mind! And definitely no rush from my side, I super appreciate your work on this project!

**Comment by eduardo-rodrigues** [comment]
Hi @gridge, such appreciation deserves the authors a start ;-) ... More seriously, and because I'm curious and user community is very important: may I ask what is your usecase for the package and your community/"background"? I find it really cool in particular when we (I mean some part of the Scikit-HEP project) reach out beyond the "obvious" customers, which are mainly HEP experimentalists. Advance thanks for the interesting feedback.

**Comment by eduardo-rodrigues** [comment]
Thanks!
