### ISSUE TITLE
Unweighted events produced from madgraph examples can't be read

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pylhe#76]
This seems to be a problem for unweighted events:

```
$ file unweighted_events.lhe.gz 
unweighted_events.lhe.gz: gzip compressed data, was "tmp_0_unweighted_events.lhe", last modified: Tue Mar 30 07:22:36 2021, max compression, original size modulo 2^32 15580732
$ python
Python 3.8.6 (default, Jan  5 2021, 00:14:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pylhe
>>> pylhe.readLHEInit("unweighted_events.lhe.gz")
weightgroup must have attribute 'type'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/feickert/Code/GitHub/Scikit-HEP/pylhe/src/pylhe/__init__.py", line 159, in readLHEInit
    wg_type = child.attrib["type"]
KeyError: 'type'
>>> pylhe.readLHEInit("unweighted_events.lhe")
weightgroup must have attribute 'type'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/feickert/Code/GitHub/Scikit-HEP/pylhe/src/pylhe/__init__.py", line 159, in readLHEInit
    wg_type = child.attrib["type"]
KeyError: 'type'
```

_Originally posted by @matthewfeickert in https://github.com/scikit-hep/pylhe/pull/74#discussion_r604688216_

**Comment by SundeMarius** [comment]
Can confirm -- I get the same error attempting to open unweighted events from MadGraph5. Since I don't need to read the "initrwgt"-block from my event file, I simply commented out that "if-block" to bypass this issue.

**Comment by matthewfeickert** [comment]
I think this is a problem between LHE versions. If you look at the file we use for testing

```python
#example.py
import skhep_testdata

if __name__ == "__main__":
    with open(skhep_testdata.data_path("pylhe-testfile-pr29.lhe"), "rb") as readfile:
        for idx, line in enumerate(readfile):
            if idx < 21:
                print(line)
```
then it show it is `LesHouchesEvents version="1.0"`
```
$ python example.py
b'<LesHouchesEvents version="1.0">\n'
b'<!-- File generated by GiBUU. For documentation see https://gibuu.hepforge.org/trac/wiki/LesHouches -->\n'
b'<header>\n'
b'     <!-- individual XML tags may follow -->\n'
b'</header>\n'
b'<init>\n'
b'       1       2  1.234567E+00  2.345678E+00     3     4     5     6     7     8\n'
b'</init>\n'
b'<event>\n'
b'     9     0  7.506240E-02  0.000000E+00  0.000000E+00  0.000000E+00\n'
b'     211    0    0    0    0    0 -3.1463804033E-01 -6.3041724109E-01  8.5343193374E+00  8.5644657479E+00  1.3800000000E-01 0. 9.\n'
b'     211    0    0    0    0    0  1.3728924857E-01  2.3422993472E-01  8.8450948490E-01  9.3547476127E-01  1.3800000000E-01 0. 9.\n'
b'     111    0    0    0    0    0  2.0614558574E-01 -5.3812028926E-01  2.4643809858E+00  2.5346177407E+00  1.3800000000E-01 0. 9.\n'
b'    -211    0    0    0    0    0 -1.9171956044E-02  3.6504699016E-01  1.6579353574E+00  1.7033556641E+00  1.3800000000E-01 0. 9.\n'
b'    2212    0    0    0    0    0 -8.7739110001E-02 -9.1192523211E-02  1.2940061744E+00  1.5978212465E+00  9.2874459818E-01 0. 9.\n'
b'    -211    0    0    0    0    0  2.7490658810E-01  9.8080122076E-02  1.9292850496E+00  1.9561130195E+00  1.3800000000E-01 0. 9.\n'
b'    -211    0    0    0    0    0  1.2944900958E-01 -4.1974185864E-01  4.7477594364E+00  4.7700318594E+00  1.3800000000E-01 0. 9.\n'
b'     211    0    0    0    0    0  2.8459044475E-01 -2.2307135479E-01  2.1228259170E+00  2.1578198313E+00  1.3800000000E-01 0. 9.\n'
b'     111    0    0    0    0    0 -3.3384740625E-01  8.6856832980E-03  8.4253178432E-02  3.7104195158E-01  1.3800000000E-01 0. 9.\n'
b'# 5    34  7.5062401567E-02   3.5771753346E+01  0.0000000000E+00  0.0000000000E+00  3.5771753346E+01   1.2219945742E+01 -1.0684353467E-01  1.1907660320E+00  1.2161321244E+01   9.2389155840E-01  1.6472156045E-01 -8.4351847155E-03  1.6379649458E-02\n'
b'</event>\n'
```

but if we now look at a `unweighted_events.lhe` file generated by `MadGraph5_aMC@NLO` `v2.9.2` we see 

```
$ head -n 2 unweighted_events.lhe
<LesHouchesEvents version="3.0">
<header>
```

So I think we need to update our testing and/or revisit what LHE versions we want to support (cc @lukasheinrich).

**Comment by JasonNielsen** [comment]
It would be great to be able to parse files written in the LHE v3.0 standard, which is almost a decade old and well established. Do all of the blocks really need to be parsed? For a start, it would be enough to ignore the new blocks (mgrwt, rscale, asrwt, etc.) and focus on the parsing of fields in the current interface.

**Comment by JasonNielsen** [comment]
The parsing of LHE v3.0 files from Pythia works fine, except if a comment line includes an ampersand!

**Comment by matthewfeickert** [comment]
Yeah, we'll be able to test things and work on fixing this once the next release of `scikit-hep-testdata` is out. Though if you already have tests and/or patches @JasonNielsen feel free to start a PR that we can iterate on.

**Comment by jhgoh** [comment]
Still having the issue with the dataset in the scikit-hep-testdata. The pylhe requires an attribute `type` in the `weightgroup` tag, but one of the testdata has attribute `name` which has the exactly same information. 
https://github.com/scikit-hep/scikit-hep-testdata/blob/main/src/skhep_testdata/data/pylhe-drell-yan-ll-lhe.gz

```xml
<weightgroup name="Central scale variation" combine="envelope">
<weight id="1" MUR="0.5"  MUF="0.5"  PDF="247000" > MUR=0.5 MUF=0.5  </weight>
```

the 'name' field had to be 'type' to run on the current pylhe.

Could pylhe be modified to allow weightgroup.name? I'm not sure on the LHE v3 standard on the weightgroup's attributes, maybe pylhe-drell-yan-ll-lhe.gz file is just malformed. My own LHE file generated with recent aMC@NLO generator did not have this issue, BTW.

**Comment by eduardo-rodrigues** [comment]
I confirm that pylhe/master can read scikit-hep-testdata's file [pylhe-drell-yan-ll-lhe.gz](https://github.com/scikit-hep/scikit-hep-testdata/blob/main/src/skhep_testdata/data/pylhe-drell-yan-ll-lhe.gz] just fine with the 3 read_lhe type of functions. This issue can safely be closed. Note that a release is imminent, and we welcome feedback :-).

BTW, I profit from the occasion to say that we always welcome new test files to improve coverage. Furthermore, do not hesitate to enhance the package if you see bits of information that are not being parsed to be provided to the user. I see from version 3 files that a lot more info could be provided, and it would be great to know if that's necessary for users, for example to you @JasonNielsen.

**Comment by eduardo-rodrigues** [comment]
Hello @jhgoh, @JasonNielsen, @matthewfeickert, I'm now closing this old issue as it seems sorted by now. But do please get in touch if you happen to have other LHE files that we should include in the test suite. That will be very helpful. Advance thanks.
